name: Jekyll site CI

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install deps & Build
        run: |
          sudo apt-get install -y graphviz ruby-full build-essential zlib1g-dev &&
          export GEM_HOME="$HOME/gems" &&
          export PATH="$HOME/gems/bin:$PATH" &&
          gem install jekyll bundler &&
          bundler install &&
          bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_outputs_folder/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
